name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'yarn'

      - name: Install yarn dependencies
        run: yarn install --immutable

      - name: Check Prettier
        run: yarn test:prettier
      - name: Check TypeScript types
        run: yarn test:types
