name: Test

on:
  push:
  workflow_dispatch:

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'yarn'
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.2.0

      - name: Install yarn dependencies
        run: yarn install --immutable
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Build Wasm
        run: yarn run build:wasm:dev

      - name: Check Prettier
        run: yarn test:prettier
      - name: Check TypeScript types
        run: yarn test:types
